version: 2
registries:
  nuget-public:
    type: nuget-feed
    url: https://api.nuget.org/v3/index.json
  bepinex:
    type: nuget-feed
    url: https://nuget.bepinex.dev/v3/index.json
updates:
  - directory: /
    package-ecosystem: nuget
    ignore:
      - dependency-name: BepInEx.Core
      - dependency-name: HarmonyX
      - dependency-name: UnityEngine.Modules
      - dependency-name: Microsoft.CodeAnalysis.CSharp
      - dependency-name: Microsoft.CodeAnalysis.Analyzers
    schedule:
      interval: daily
    registries:
      - nuget-public
      - bepinex 
  - directory: /
    package-ecosystem: github-actions
    schedule:
      interval: daily
      